# fly.toml app configuration file generated for hack05 on 2023-04-21T10:30:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hack05"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
